services:
  db:
    image: postgres:15
    container_name: ModUsuariosContainer
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdusuarios
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
