services:
  base:
    build:
      context: /home/renzo/HLC/devops/docker/ModuloUsuarios
      dockerfile: ./dockerfile/base/Dockerfile
    container_name: moduloUsuarioctr
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_PASSWORD=admin
      - DB_NAME=bdusuarios
    depends_on:
      - db
    ports:
     - "3000:3000"
  db:
    image: postgres:15
    container_name: dbpostgres15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bdusuarios
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
